services:
  - type: web
    name: card-validation
    runtime: node
    buildCommand: npm install && npx tsc
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
